package webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-10-29T22:33:34.837+02:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://www.ourproducts.de", name = "Product")
@XmlSeeAlso({ObjectFactory.class})
public interface Product {

    @WebMethod(action = "list")
    @Action(input = "list", output = "http://www.ourproducts.de/Product/listAllProductsResponse")
    @RequestWrapper(localName = "listAllProducts", targetNamespace = "http://www.ourproducts.de", className = "webservices.ListAllProducts")
    @ResponseWrapper(localName = "listAllProductsResponse", targetNamespace = "http://www.ourproducts.de", className = "webservices.ListAllProductsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> listAllProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod(action = "categories")
    @Action(input = "categories", output = "http://www.ourproducts.de/Product/listProductCategoriesResponse")
    @RequestWrapper(localName = "listProductCategories", targetNamespace = "http://www.ourproducts.de", className = "webservices.ListProductCategories")
    @ResponseWrapper(localName = "listProductCategoriesResponse", targetNamespace = "http://www.ourproducts.de", className = "webservices.ListProductCategoriesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> listProductCategories();

    @WebMethod(action = "add")
    @Action(input = "add", output = "http://www.ourproducts.de/Product/addProductResponse")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://www.ourproducts.de", className = "webservices.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://www.ourproducts.de", className = "webservices.AddProductResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
